services:
  rabbitMQ:
    container_name: rabbitMQ
    hostname: rabbitmq
    image: rabbitmq:3.11.13-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitnet
  account:
    container_name: account-service
    image: maasmai/account:v1.0.0
    restart: always
    depends_on:
      - rabbitMQ
    ports:
      - 8080:8080
    networks:
      - rabbitnet
    environment:
      SPRING_RABBITMQ_HOST: rabbitMQ
  transaction:
    container_name: transaction-service
    image: maasmai/transaction:v1.0.0
    depends_on:
      - rabbitMQ
    restart: always
    networks:
      - rabbitnet
    environment:
      SPRING_RABBITMQ_HOST: rabbitMQ
networks:
  rabbitnet:


