spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  rabbitmq:
    username: user
    password: password
  cloud:
    stream:
      rabbit:
        bindings:
          startTransaction-out-0:
            producer:
              transacted: true
      bindings:
        startTransaction-out-0:
          destination: Transaction